    apiVersion: v1
    kind: Service
    metadata:
      name: bbc-service
    spec:
      selector:
        app: bbc
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
      type: LoadBalancer
